/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 16-mei-2019 17:26:13 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'AnalysisEntity'
;

DROP TABLE IF EXISTS 'StakeholderEntity'
;

DROP TABLE IF EXISTS 'OnionDiagramEntity'
;

DROP TABLE IF EXISTS 'OnionDiagramStakeholderEntity'
;

DROP TABLE IF EXISTS 'StakeholderConnectionEntity'
;

DROP TABLE IF EXISTS 'OnionRingEntity'
;

DROP TABLE IF EXISTS 'StakeholderConnectionGroupEntity'
;

DROP TABLE IF EXISTS 'ForceFieldDiagramEntity'
;

DROP TABLE IF EXISTS 'ForceFieldDiagramStakeholderEntity'
;

DROP TABLE IF EXISTS 'AttitudeImpactDiagramEntity'
;

DROP TABLE IF EXISTS 'AttitudeImpactDiagramStakeholderEntity'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'AnalysisEntity'
(
	'AnalysisEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'StakeholderId' INTEGER
)
;

CREATE TABLE 'StakeholderEntity'
(
	'StakeholderEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'AnalysisEntityId' INTEGER,
	'Name' TEXT,
	'Type' TINYINT NOT NULL,
	'Order' INTEGER,
	CONSTRAINT 'FK_StakeholderEntity_AnalysisEntity' FOREIGN KEY ('AnalysisEntityId') REFERENCES 'AnalysisEntity' ('AnalysisEntityId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'OnionDiagramEntity'
(
	'OnionDiagramId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'AnalysisEntityId' INTEGER,
	'Name' TEXT,
	'Asymmetry' REAL NOT NULL DEFAULT 0.0,
	'Order' INTEGER NOT NULL,
	CONSTRAINT 'FK_OnionDiagramEntity_AnalysisEntity' FOREIGN KEY ('AnalysisEntityId') REFERENCES 'AnalysisEntity' ('AnalysisEntityId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'OnionDiagramStakeholderEntity'
(
	'OnionDiagramStakeholderEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'StakeholderEntityId' INTEGER,
	'OnionDiagramId' INTEGER,
	'Left' REAL NOT NULL DEFAULT 0.5,
	'Top' REAL NOT NULL DEFAULT 0.5,
	'Order' INTEGER NOT NULL,
	CONSTRAINT 'FK_OnionDiagramStakeholderEntity_OnionDiagramEntity' FOREIGN KEY ('OnionDiagramId') REFERENCES 'OnionDiagramEntity' ('OnionDiagramId') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_OnionDiagramStakeholderEntity_StakeholderEntity' FOREIGN KEY ('StakeholderEntityId') REFERENCES 'StakeholderEntity' ('StakeholderEntityId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'StakeholderConnectionEntity'
(
	'StakeholderConnectionEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'StakeholderConnectionGroupEntityId' INTEGER,
	'StakeholderFromEntityId' INTEGER,
	'StakeholderToEntityId' INTEGER,
	'OnionDiagramId' INTEGER,
	'Order' INTEGER NOT NULL,
	CONSTRAINT 'FK_StakeholderConnectionEntity_OnionDiagramEntity' FOREIGN KEY ('OnionDiagramId') REFERENCES 'OnionDiagramEntity' ('OnionDiagramId') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_StakeholderConnectionEntity_OnionDiagramStakeholderEntity' FOREIGN KEY ('StakeholderFromEntityId') REFERENCES 'OnionDiagramStakeholderEntity' ('OnionDiagramStakeholderEntityId') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_StakeholderConnectionEntity_OnionDiagramStakeholderEntity_02' FOREIGN KEY ('StakeholderToEntityId') REFERENCES 'OnionDiagramStakeholderEntity' ('OnionDiagramStakeholderEntityId') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_StakeholderConnectionEntity_StakeholderConnectionGroupEntity' FOREIGN KEY ('StakeholderConnectionGroupEntityId') REFERENCES 'StakeholderConnectionGroupEntity' ('StakeholderConnectionGroupEntityId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'OnionRingEntity'
(
	'OnrionRingEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'OnionDiagramId' INTEGER,
	'Percentage' REAL NOT NULL,
	'BackgroundColor' TEXT,
	'StrokeColor' TEXT,
	'StrokeThickness' REAL NOT NULL DEFAULT 1.0,
	'Order' INTEGER,
	CONSTRAINT 'FK_OnionRingEntity_OnionDiagramEntity' FOREIGN KEY ('OnionDiagramId') REFERENCES 'OnionDiagramEntity' ('OnionDiagramId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'StakeholderConnectionGroupEntity'
(
	'StakeholderConnectionGroupEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'OnionDiagramId' INTEGER,
	'Name' TEXT,
	'Color' TEXT,
	'Visible' TEXT,
	'StrokeThickness' REAL,
	'Order' INTEGER NOT NULL,
	CONSTRAINT 'FK_StakeholderConnectionGroupEntity_OnionDiagramEntity' FOREIGN KEY ('OnionDiagramId') REFERENCES 'OnionDiagramEntity' ('OnionDiagramId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'ForceFieldDiagramEntity'
(
	'ForceFieldDiagramEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'AnalysisEntityId' INTEGER,
	'Name' TEXT,
	'Order' INTEGER,
	CONSTRAINT 'FK_ForceFieldDiagramEntity_AnalysisEntity' FOREIGN KEY ('AnalysisEntityId') REFERENCES 'AnalysisEntity' ('AnalysisEntityId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'ForceFieldDiagramStakeholderEntity'
(
	'ForceFieldDiagramStakeholderEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'StakeholderEntityId' INTEGER,
	'ForceFieldDiagramEntityId' INTEGER,
	'Interest' REAL,
	'Influence' REAL,
	'Order' INTEGER,
	CONSTRAINT 'FK_ForceFieldDiagramStakeholderEntity_ForceFieldDiagramEntity' FOREIGN KEY ('ForceFieldDiagramEntityId') REFERENCES 'ForceFieldDiagramEntity' ('ForceFieldDiagramEntityId') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_ForceFieldDiagramStakeholderEntity_StakeholderEntity' FOREIGN KEY ('StakeholderEntityId') REFERENCES 'StakeholderEntity' ('StakeholderEntityId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'AttitudeImpactDiagramEntity'
(
	'AttitudeImpactDiagramEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'AnalysisEntityId' INTEGER,
	'AnalysisId' INTEGER,
	'Name' TEXT,
	'Order' INTEGER,
	CONSTRAINT 'FK_AttitudeImpactDiagramEntity_AnalysisEntity' FOREIGN KEY ('AnalysisEntityId') REFERENCES 'AnalysisEntity' ('AnalysisEntityId') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'AttitudeImpactDiagramStakeholderEntity'
(
	'AttitudeImpactDiagramStakeholderEntityId' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'AttitudeImpactDiagramEntityId' INTEGER,
	'StakeholderEntityId' INTEGER,
	'Attitude' REAL,
	'Impact' REAL,
	'Order' INTEGER,
	CONSTRAINT 'FK_AttitudeImpactDiagramStakeholderEntity_AttitudeImpactDiagramEntity' FOREIGN KEY ('AttitudeImpactDiagramEntityId') REFERENCES 'AttitudeImpactDiagramEntity' ('AttitudeImpactDiagramEntityId') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_AttitudeImpactDiagramStakeholderEntity_StakeholderEntity' FOREIGN KEY ('StakeholderEntityId') REFERENCES 'StakeholderEntity' ('StakeholderEntityId') ON DELETE No Action ON UPDATE No Action
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_StakeholderEntity_AnalysisEntity'
 ON 'StakeholderEntity' ('AnalysisEntityId' ASC)
;

CREATE INDEX 'IXFK_OnionDiagramEntity_AnalysisEntity'
 ON 'OnionDiagramEntity' ('AnalysisEntityId' ASC)
;

CREATE INDEX 'IXFK_OnionDiagramStakeholderEntity_OnionDiagramEntity'
 ON 'OnionDiagramStakeholderEntity' ('OnionDiagramId' ASC)
;

CREATE INDEX 'IXFK_OnionDiagramStakeholderEntity_StakeholderEntity'
 ON 'OnionDiagramStakeholderEntity' ('StakeholderEntityId' ASC)
;

CREATE INDEX 'IXFK_StakeholderConnectionEntity_OnionDiagramEntity'
 ON 'StakeholderConnectionEntity' ('OnionDiagramId' ASC)
;

CREATE INDEX 'IXFK_StakeholderConnectionEntity_OnionDiagramStakeholderEntity'
 ON 'StakeholderConnectionEntity' ('StakeholderFromEntityId' ASC)
;

CREATE INDEX 'IXFK_StakeholderConnectionEntity_OnionDiagramStakeholderEntity_02'
 ON 'StakeholderConnectionEntity' ('StakeholderToEntityId' ASC)
;

CREATE INDEX 'IXFK_StakeholderConnectionEntity_StakeholderConnectionGroupEntity'
 ON 'StakeholderConnectionEntity' ('StakeholderConnectionGroupEntityId' ASC)
;

CREATE INDEX 'IXFK_OnionRingEntity_OnionDiagramEntity'
 ON 'OnionRingEntity' ('OnionDiagramId' ASC)
;

CREATE INDEX 'IXFK_StakeholderConnectionGroupEntity_OnionDiagramEntity'
 ON 'StakeholderConnectionGroupEntity' ('OnionDiagramId' ASC)
;

CREATE INDEX 'IXFK_ForceFieldDiagramEntity_AnalysisEntity'
 ON 'ForceFieldDiagramEntity' ('AnalysisEntityId' ASC)
;

CREATE INDEX 'IXFK_ForceFieldDiagramStakeholderEntity_ForceFieldDiagramEntity'
 ON 'ForceFieldDiagramStakeholderEntity' ('ForceFieldDiagramEntityId' ASC)
;

CREATE INDEX 'IXFK_ForceFieldDiagramStakeholderEntity_StakeholderEntity'
 ON 'ForceFieldDiagramStakeholderEntity' ('StakeholderEntityId' ASC)
;

CREATE INDEX 'IXFK_AttitudeImpactDiagramEntity_AnalysisEntity'
 ON 'AttitudeImpactDiagramEntity' ('AnalysisEntityId' ASC)
;

CREATE INDEX 'IXFK_AttitudeImpactDiagramStakeholderEntity_AttitudeImpactDiagramEntity'
 ON 'AttitudeImpactDiagramStakeholderEntity' ('AttitudeImpactDiagramEntityId' ASC)
;

CREATE INDEX 'IXFK_AttitudeImpactDiagramStakeholderEntity_StakeholderEntity'
 ON 'AttitudeImpactDiagramStakeholderEntity' ('StakeholderEntityId' ASC)
;
