//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalysisEntity()
        {
            this.AttitudeImpactDiagramEntity = new HashSet<AttitudeImpactDiagramEntity>();
            this.ForceFieldDiagramEntity = new HashSet<ForceFieldDiagramEntity>();
            this.OnionDiagramEntity = new HashSet<OnionDiagramEntity>();
            this.StakeholderEntity = new HashSet<StakeholderEntity>();
        }
    
        public long AnalysisEntityId { get; set; }
        public Nullable<long> StakeholderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttitudeImpactDiagramEntity> AttitudeImpactDiagramEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForceFieldDiagramEntity> ForceFieldDiagramEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnionDiagramEntity> OnionDiagramEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StakeholderEntity> StakeholderEntity { get; set; }
    }
}
