//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttitudeImpactDiagramStakeholderEntity
    {
        public long AttitudeImpactDiagramStakeholderEntityId { get; set; }
        public long AttitudeImpactDiagramEntityId { get; set; }
        public long StakeholderEntityId { get; set; }
        public double Attitude { get; set; }
        public double Impact { get; set; }
        public long Order { get; set; }
    
        public virtual AttitudeImpactDiagramEntity AttitudeImpactDiagramEntity { get; set; }
        public virtual StakeholderEntity StakeholderEntity { get; set; }
    }
}
