//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForceFieldDiagramStakeholderEntity
    {
        public long ForceFieldDiagramStakeholderEntityId { get; set; }
        public long StakeholderEntityId { get; set; }
        public long ForceFieldDiagramEntityId { get; set; }
        public Nullable<double> Interest { get; set; }
        public Nullable<double> Influence { get; set; }
        public long Rank { get; set; }
        public long Order { get; set; }
    
        public virtual ForceFieldDiagramEntity ForceFieldDiagramEntity { get; set; }
        public virtual StakeholderEntity StakeholderEntity { get; set; }
    }
}
