//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnionRingEntity
    {
        public long OnrionRingEntityId { get; set; }
        public long OnionDiagramId { get; set; }
        public double Percentage { get; set; }
        public string BackgroundColor { get; set; }
        public string StrokeColor { get; set; }
        public double StrokeThickness { get; set; }
        public long Order { get; set; }
    
        public virtual OnionDiagramEntity OnionDiagramEntity { get; set; }
    }
}
