//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnionDiagramEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnionDiagramEntity()
        {
            this.OnionDiagramStakeholderEntity = new HashSet<OnionDiagramStakeholderEntity>();
            this.OnionRingEntity = new HashSet<OnionRingEntity>();
            this.StakeholderConnectionEntity = new HashSet<StakeholderConnectionEntity>();
            this.StakeholderConnectionGroupEntity = new HashSet<StakeholderConnectionGroupEntity>();
        }
    
        public long OnionDiagramId { get; set; }
        public Nullable<long> AnalysisEntityId { get; set; }
        public string Name { get; set; }
        public double Asymmetry { get; set; }
        public long Order { get; set; }
    
        public virtual AnalysisEntity AnalysisEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnionDiagramStakeholderEntity> OnionDiagramStakeholderEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnionRingEntity> OnionRingEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StakeholderConnectionEntity> StakeholderConnectionEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StakeholderConnectionGroupEntity> StakeholderConnectionGroupEntity { get; set; }
    }
}
