//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnionDiagramStakeholderEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnionDiagramStakeholderEntity()
        {
            this.StakeholderConnectionEntity = new HashSet<StakeholderConnectionEntity>();
            this.StakeholderConnectionEntity1 = new HashSet<StakeholderConnectionEntity>();
        }
    
        public long OnionDiagramStakeholderEntityId { get; set; }
        public Nullable<long> StakeholderEntityId { get; set; }
        public Nullable<long> OnionDiagramId { get; set; }
        public double Left { get; set; }
        public double Top { get; set; }
        public long Order { get; set; }
    
        public virtual OnionDiagramEntity OnionDiagramEntity { get; set; }
        public virtual StakeholderEntity StakeholderEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StakeholderConnectionEntity> StakeholderConnectionEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StakeholderConnectionEntity> StakeholderConnectionEntity1 { get; set; }
    }
}
