//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StakeholderEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StakeholderEntity()
        {
            this.AttitudeImpactDiagramStakeholderEntity = new HashSet<AttitudeImpactDiagramStakeholderEntity>();
            this.ForceFieldDiagramStakeholderEntity = new HashSet<ForceFieldDiagramStakeholderEntity>();
            this.OnionDiagramStakeholderEntity = new HashSet<OnionDiagramStakeholderEntity>();
        }
    
        public long StakeholderEntityId { get; set; }
        public Nullable<long> AnalysisEntityId { get; set; }
        public string Name { get; set; }
        public byte Type { get; set; }
        public Nullable<long> Order { get; set; }
    
        public virtual AnalysisEntity AnalysisEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttitudeImpactDiagramStakeholderEntity> AttitudeImpactDiagramStakeholderEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForceFieldDiagramStakeholderEntity> ForceFieldDiagramStakeholderEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnionDiagramStakeholderEntity> OnionDiagramStakeholderEntity { get; set; }
    }
}
