//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalysisEntity> AnalysisEntities { get; set; }
        public virtual DbSet<AttitudeImpactDiagramEntity> AttitudeImpactDiagramEntities { get; set; }
        public virtual DbSet<AttitudeImpactDiagramStakeholderEntity> AttitudeImpactDiagramStakeholderEntities { get; set; }
        public virtual DbSet<ForceFieldDiagramEntity> ForceFieldDiagramEntities { get; set; }
        public virtual DbSet<ForceFieldDiagramStakeholderEntity> ForceFieldDiagramStakeholderEntities { get; set; }
        public virtual DbSet<OnionDiagramEntity> OnionDiagramEntities { get; set; }
        public virtual DbSet<OnionDiagramStakeholderEntity> OnionDiagramStakeholderEntities { get; set; }
        public virtual DbSet<OnionRingEntity> OnionRingEntities { get; set; }
        public virtual DbSet<StakeholderConnectionEntity> StakeholderConnectionEntities { get; set; }
        public virtual DbSet<StakeholderConnectionGroupEntity> StakeholderConnectionGroupEntities { get; set; }
        public virtual DbSet<StakeholderEntity> StakeholderEntities { get; set; }
        public virtual DbSet<StakeholderTypeEntity> StakeholderTypeEntities { get; set; }
        public virtual DbSet<VersionEntity> VersionEntities { get; set; }
    }
}
