//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalysisEntity> AnalysisEntity { get; set; }
        public virtual DbSet<AttitudeImpactDiagramEntity> AttitudeImpactDiagramEntity { get; set; }
        public virtual DbSet<AttitudeImpactDiagramStakeholderEntity> AttitudeImpactDiagramStakeholderEntity { get; set; }
        public virtual DbSet<ForceFieldDiagramEntity> ForceFieldDiagramEntity { get; set; }
        public virtual DbSet<ForceFieldDiagramStakeholderEntity> ForceFieldDiagramStakeholderEntity { get; set; }
        public virtual DbSet<OnionDiagramEntity> OnionDiagramEntity { get; set; }
        public virtual DbSet<OnionDiagramStakeholderEntity> OnionDiagramStakeholderEntity { get; set; }
        public virtual DbSet<OnionRingEntity> OnionRingEntity { get; set; }
        public virtual DbSet<StakeholderConnectionEntity> StakeholderConnectionEntity { get; set; }
        public virtual DbSet<StakeholderConnectionGroupEntity> StakeholderConnectionGroupEntity { get; set; }
        public virtual DbSet<StakeholderEntity> StakeholderEntity { get; set; }
    }
}
