//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StakeholderConnectionEntity
    {
        public long StakeholderConnectionEntityId { get; set; }
        public Nullable<long> StakeholderConnectionGroupEntityId { get; set; }
        public Nullable<long> StakeholderFromEntityId { get; set; }
        public Nullable<long> StakeholderToEntityId { get; set; }
        public Nullable<long> OnionDiagramId { get; set; }
        public long Order { get; set; }
    
        public virtual OnionDiagramEntity OnionDiagramEntity { get; set; }
        public virtual OnionDiagramStakeholderEntity OnionDiagramStakeholderEntity { get; set; }
        public virtual OnionDiagramStakeholderEntity OnionDiagramStakeholderEntity1 { get; set; }
        public virtual StakeholderConnectionGroupEntity StakeholderConnectionGroupEntity { get; set; }
    }
}
