//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StakeholderAnalysis.Storage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StakeholderTypeEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StakeholderTypeEntity()
        {
            this.StakeholderEntities = new HashSet<StakeholderEntity>();
        }
    
        public long StakeholderTypeId { get; set; }
        public long AnalysisEntityId { get; set; }
        public string Name { get; set; }
        public byte Icontype { get; set; }
        public string Color { get; set; }
        public long Order { get; set; }
    
        public virtual AnalysisEntity AnalysisEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StakeholderEntity> StakeholderEntities { get; set; }
    }
}
